title: General Content Page

fields:
  headerHeadline:
    label: Header Settings 
    type: headline

  title:
    label: Title
    type: text
    required: true

  subtitle:
    label: Subtitle
    type: text
    help: Customize the site's subtitle. Leave blank to use page title.

  headerImage:
    label: Header Image
    type: image
    help: Select an image to customize the background of the header section. 

  contentHeadline:
    label: Content 
    type: headline

  builderContent:
    label: Content Sections
    type: builder
    fieldsets: 
      contentText: 
        label: Body Text
        snippet: builder/contentText
        fields:
          contentText:
            label: Text Content
            type:  wysiwyg
            required: true
            help: Enter text content for the section
            buttons:
              - h3
              - h4
              - h5
              - bold
              - italic
              - anchor
              - orderedlist 
              - unorderedlist
              - removeFormat
      heading: 
        label: Heading
        snippet: builder/heading
        fields:
          headingInfo:
            type: info
            text: >
              To emphasizes portion wrap with html tag: ```My Text <em>-- With Emphasis!</em>```
          contentHeading:
            label: Heading
            type: text
            required: true
          alignment:
            label: Alignement
            type: select
            default: default
            options: 
              default: Default
              center: Center
      markdownContent: 
        label: Markdown Content
        snippet: builder/markdownText
        fields:
          contentInfo:
            label: Markdown Text
            type: info
            text: >
              Use markdown to create content. See (link: https://getkirby.com/docs/content/text text:Help Page popup: yes)


              To center, wrap text in html block: ```<p class="center">My text </p>```

              To create button link use class "btn btn-brand pill" i.e.: "&#40;link: http://www.link.com text: My Link class: btn btn-brand pill&#41;"

              When linking to a pdf file use "&#40;file: myFileName.pdf ...&#41;" instead of "&#40;link ...&#41;"
          contentText:
            label: Text Content
            type:  textarea
            required: true
            help: Enter text content for the section
      contentImage:
        label: Image
        snippet: builder/contentImage
        fields:
          contentImage: 
            label: Image
            type: image
            help: Select an image in the content section
            required: true
          alignment:
            label: Image Alignment
            type: select
            options:
              fullWidth: No Alignment
              imageLeft: Image to left
              imageRight: Image to right
            default: imageLeft
          imageSize:
            label: Image Size
            type: select
            options:
              medium: Medium
              large: Large
              full: Full Size
            default: medium
          caption:
            label: Caption
            type: text
      spacer:
        label: Spacer
        entry: >
          Space between sections: {{spacing}} pixels
        fields:
          spacing:
            label: Spacing
            type: number
            min: 0
            max: 150
            help: Set amount of pixels to add between previous and next section.
            default: 100
      horizontalRule:
        label: Line
        entry: >
          <hr/>
        fields:
          fieldsInfo:
            type: info
            text: A horizontal rule will be included