title: General Content Page

pages:
  template: teamMember

fields:
  title:
    label: Title
    type: text
    required: true

  subtitle:
    label: Subtitle
    type: text
    help: Customize the site's subtitle. Leave blank to use page title.

  headerImage:
    label: Header Image
    type: image
    help: Select an image to customize the background of the header section. 

  headlineContentSections:
    label: Content Sections
    type: headline

  contentSectionsInfo:
    type: info
    label: Managing Content Sections
    text: >
      Enter content displayed in rows. Blank fields are not displayed.
      
      When including an image, select an orientation (right or left) to manage whether the image is displayed before or after text.     

  contentHeading:
    label: Section Heading
    type: text
    help: Enter a heading for the content section.

  contentText:
    label: Text
    type:  textarea
  
  contentImage:
    label: Section Image
    type: image
    width: 3/4
    
  contentOrientation:
    label: Image Orientation
    type: select
    options:
      imageLeft: Image to left
      imageRight: Image to right
    default: imageLeft
    width: 1/4

  line-content-1:
    type: line

  contentHeading2:
    label: Section Heading
    type: text
    help: Enter a heading for the content section.

  contentText2:
    label: Text
    type:  textarea
  
  contentImage2:
    label: Section Image
    type: image
    width: 3/4
    
  contentOrientation2:
    label: Image Orientation
    type: select
    options:
      imageLeft: Image to left
      imageRight: Image to right
    default: imageRight
    width: 1/4
  
  headlineStatBar:
    label: Stat Bar
    type: headline

  statBarBackgroundImage:
    label: Background Image
    type: image
    help: Full width background image for stat bar

  statNumberOne:
    label: Stat Number One
    type: number
    width: 1/4

  statTitleOne:
    label: Stat Title One
    type: text
    width: 3/4
  
  statNumberTwo:
    label: Stat Number Two
    type: number
    width: 1/4

  statTitleTwo:
    label: Stat Title Two
    type: text
    width: 3/4

  statNumberThree:
    label: Stat Number Three
    type: number
    width: 1/4

  statTitleThree:
    label: Stat Title Three
    type: text
    width: 3/4
  
  statNumberFour:
    label: Stat Number Four
    type: number
    width: 1/4

  statTitleFour:
    label: Stat Title Four
    type: text
    width: 3/4

  headlineTeam:
    label: Team Members
    type: headline
  
  teamHeading:
    label: Heading for Team Members Section
    default: Our Team
    type: text

  teamInfo:
    type: info
    label: Managing Team Members
    text: >
      Use the Pages > "+ Add" button to create new team members in the team members section.

      To reorder the team members click Pages > "Edit" and drag and drop to change the order.
      
      Please note, urls of subpages are ignored.