title: General Content Page

fields:
  title:
    label: Title
    type: text
    required: true

  subtitle:
    label: Subtitle
    type: text
    help: Customize the site's subtitle. Leave blank to use page title.

  headerImage:
    label: Header Image
    type: image
    help: Select an image to customize the background of the header section. 

  content:
    label: Text
    type:  textarea