title: Recipe

pages: false

files: true

fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type: textarea
  tags:
    label: Tags
    type: tags
    required: true
  ingredients:
    label: Ingredients
    type: wysiwyg
    required: true
  directions:
    label: Directions
    type: wysiwyg
    required: true
  credits:
    label: Credits
    type: text
    help: Enter any recipe credits