title: Site

fields:

  headlineMeta:
    label: Meta Info Settings
    type: headline

  title:
    label: Title
    type:  text

  description:
    label: Description
    type:  textarea

  headlineContactInfo:
    label: Contact Info Settings
    type: headline
    
  address:
    label: Address
    type: text

  phone:
    label: Phone Number
    type: tel
    width: 1/2

  email:
    label: E-mail Address
    type: email
    width: 1/2

  headlineHeader:
    label: Header Settings
    type: headline

  logo:
    label: Logo
    type: image

  headerImage:
    label: Default Header Image
    type: image
    help: Select an image to use as the default background of the header section on sub pages. 

  headlineFooter:
    label: Footer Settings 
    type: headline

  footerLogo:
    label: Footer Logo
    type: image

  newsletterFormHeading: 
    label: Newsletter Form Heading
    type: text
    default: Stay Connected!

  mailchimpFormAction:
    label: Mailchimp form action
    type: text
    help: Enter the 'action' value in the <form> element in the mailchimp embed code

  copyright:
    label: Copyright
    type: textarea

  awardAssociationImages:
    label: Award & Association Images
    type: structure
    style: table
    fields:
      image:
        label: Image
        type: image
        required: true

      title:
        label: Title
        type: text

      url:
        label: URL
        type: url

      hideInMobile:
        label: Hide In Moble
        type: toggle
        default: false

  headlineSocial:
    label: Social Settings 
    type: headline

  facebook:
    label: Facebook URL
    type: url

  instagram:
    label: Instagram URL
    type: url

  calloutImages:
    label: Callout Background Images
    help: Add background images (475px x 270px) for the footer callout section.
    type: structure
    style: table
    fields:
      image:
        label: Image
        type: image
        required: true