title: Site

fields:
  title:
    label: Title
    type:  text

  description:
    label: Description
    type:  textarea
    
  address:
    label: Address
    type: text

  phone:
    label: Phone Number
    type: tel
    width: 1/2

  email:
    label: E-mail Address
    type: email
    width: 1/2

  copyright:
    label: Copyright
    type:  textarea

